### ISSUE TITLE
Programa para de abrir .obj depois de dar New

### ISSUE THREAD

**Issue by JPTIZ** [thurbridi/py-rudolph#51]
Passos pra reproduzir:
1. Abra o py-rudolph;
2. Abra um arquivo .obj;
3. File -> New;
4. Tente abrir um .obj de novo;
5. Boom:

```
Traceback (most recent call last):
  File "/home/jptiz/dev/usc/cg/py-rudolph/src/windows.py", line 386, in on_open_file
    self.scene.update_ndc()
  File "/home/jptiz/dev/usc/cg/py-rudolph/src/scene.py", line 35, in update_ndc
    obj.update_ndc(self.window)
  File "/home/jptiz/dev/usc/cg/py-rudolph/src/graphics.py", line 39, in update_ndc
    t_matrix = ndc_matrix(window)
  File "/home/jptiz/dev/usc/cg/py-rudolph/src/transformations.py", line 46, in ndc_matrix
    @ scale_matrix(2 / window.width, 2 / window.height)
AttributeError: 'NoneType' object has no attribute 'centroid'
```

**Comment by thurbridi** [comment]
`on_new_file()` criava uma nova `Scene` com `window=None`.

O problema foi corrigido na branch curve-persistence #56.
